#! /usr/bin/env python
'''
Main file for RadioPi, an interface between various programs and an LCD, to
function as a sort of transistor radio/media player.

Copyright 2014 Martin Grønholdt

This file is part of RadioPi.

RadioPi is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

RadioPi is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with RadioPi.  If not, see <http://www.gnu.org/licenses/>.
'''
from radiopi.radiopi import RadioPi

def main():
    '''
    The entry point.
    '''
    try:
        radiopi = RadioPi()
        radiopi.main_loop()
    finally:
        radiopi.ui.close()
        radiopi.players.close()

if __name__ == '__main__':
    main()